// Forecate for multiple cities

export const WEATHER_REQUEST_START = 'WEATHER_REQUEST_START';
export const WEATHER_REQUEST_SUCCESS = 'WEATHER_REQUEST_SUCCESS';
export const WEATHER_REQUEST_FAILURE = 'WEATHER_REQUEST_FAILURE';


// Set Default Attributes
export const SET_DEFAULT_FILTER_ATTS = 'SET_DEFAULT_FILTER_ATTS';
export const RESET_DEFAULT_FILTER_ATTS = 'RESET_DEFAULT_FILTER_ATTS';

// Forecast for particular city
export const FETCH_CITYWEATHER_REQUEST = 'FETCH_CITYWEATHER_REQUEST';
export const FETCH_CITYWEATHER_SUCCESS = 'FETCH_CITYWEATHER_SUCCESS';
export const FETCH_CITYWEATHER_FAILURE= 'FETCH_CITYWEATHER_FAILURE';