// Forecast for particular city
export const FETCH_CITYWEATHER_REQUEST = 'FETCH_CITYWEATHER_REQUEST';
export const FETCH_CITYWEATHER_SUCCESS = 'FETCH_CITYWEATHER_SUCCESS';
export const FETCH_CITYWEATHER_FAILURE= 'FETCH_CITYWEATHER_FAILURE';